"""Model: Some more fields in actor. New table: Film.

Revision ID: d4e01f13bdaf
Revises: 5fced99881a9
Create Date: 2022-11-13 15:09:53.815942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e01f13bdaf'
down_revision = '5fced99881a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_release', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actor', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=False))
    op.alter_column('actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('actor', 'catchphrase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('actor', 'age')
    op.drop_column('actor', 'gender')
    op.drop_table('film')
    # ### end Alembic commands ###
